accounts/urls.py
from django.contrib.auth import views, logout
from django.urls import path
from django.contrib import admin
from .views import registration, registration1
from . import views as local_view

urlpatterns = [

    path('login/', local_view.user_login,  name='login'),
    path('phone/', local_view.add_phone,  name='add_phone'),
    path('logout/', local_view.logout_view, name='logout'),
    path('password-reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('', registration, name='register'),
    path('registration1', registration1, name='registration1')

]

ajax/urls.py
from django.urls import path
from . import views

app_name = 'ajax'

urlpatterns = [
    path('First', views.FirstAjax, name='First'),
]

site1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users', include('users.urls')),
    path('ajax/', include('ajax.urls')),
    path('users/', include('accounts.urls')),
    path('room/', include('room.urls')),
    path('department-events/', include('department_events.urls')),
] + [
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# http: // 127.0.0.1: 8000 / accounts / login / длявхода,
# http: // 127.0.0.1: 8000 / accounts / logout / длявыхода,
# http: // 127.0.0.1: 8000 / accounts / password - change / длясменыпароля,
# http: // 127.0.0.1: 8000 / accounts / password - reset / для сброс пароля.
#http://127.0.0.1:8000/registration/

accounts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User


# Create your models here.
class Profile(models.Model):
    class Status(models.TextChoices):
        NO = '0', 'Ждет подтверждения'
        YES = '1', 'Подтвержден'

    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Username')
    first_name = models.CharField(max_length=300, verbose_name='Имя', default='')
    last_name = models.CharField(max_length=300, verbose_name='Фамилия', default='')
    phone = models.CharField(max_length=20, verbose_name="Номер телефона", default='')
    podrazdelenie = models.ForeignKey(to='Podrazdelenie', verbose_name='Подразделение', on_delete=models.CASCADE, null=True)
    dolgnost =  models.ForeignKey(to='Dolgnost', verbose_name='Должность', on_delete=models.CASCADE, null=True)
    status = models.CharField(choices=Status.choices, default=Status.NO, max_length=50)
    sort_index = models.IntegerField(default=5, verbose_name='Индекс сортировки')
    is_boss = models.BooleanField(default=False, verbose_name='Начальник')
    is_bigboss = models.BooleanField(default=False, verbose_name='Завпост')
    is_pomreg = models.BooleanField(default=False, verbose_name='Помреж')

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)


    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()
        new = Profile.objects.get(user=instance)
        new.first_name = instance.first_name
        new.last_name = instance.last_name
        new.save()


    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'


class Podrazdelenie(models.Model):
    name = models.CharField(max_length=300, verbose_name="Подразделение",)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Подразделение'
        verbose_name_plural = 'Подразделения'


class Dolgnost(models.Model):
    name = models.CharField(max_length=300, verbose_name="Должность", )
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'Должность'
        verbose_name_plural = 'Должности'

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import TextInput, ChoiceField, Select, SelectMultiple
from django.forms.widgets import ChoiceWidget
from django.utils.deconstruct import deconstructible
from django.core.exceptions import ValidationError

from .models import Profile





class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)



class RegisterForm(UserCreationForm):

    class Meta:
        model=User
        fields = ['username', 'first_name', 'last_name', 'password1','password2']

class Phone(forms.ModelForm):
    phone = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}), max_length=12, min_length=11)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['podrazdelenie'].empty_label = 'Выберите подразделение'
        self.fields['dolgnost'].empty_label = 'Выберите должность'



    class Meta:
        model = Profile
        fields = ['phone', 'podrazdelenie', 'dolgnost',]

    def clean_phone(self):

        phone = self.cleaned_data['phone']
        ALLOWED_CHARS = '+1234567890-'
        phone_digits = ''
        for i in phone:
            if str(i).isdigit():
                phone_digits += i


        if not (set(phone) <= set(ALLOWED_CHARS)):
            raise ValidationError("Номер должен состоять из цифр")
        elif not ("+7" in phone[:2] or "8" == phone[0]):
            raise ValidationError("Номер должен начинаться на '+7' или '8' и состоять из 10 цифр, не считая кода страны")
        elif len(phone_digits) != 11:
            raise ValidationError(
                "Номер должен состоять из 10 цифр, не считая кода страны")
        else:
            return phone



class FormValid(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name' , 'phone', 'podrazdelenie', 'dolgnost',]
        widgets = {
            'first_name': TextInput(attrs={
                'class': 'form-control',
            }),
            'last_name': TextInput(attrs={
                'class': 'form-control',
            }),
            'phone': TextInput(attrs={
                'class': 'form-control',
            }),
            'podrazdelenie': Select(attrs={
                'class': 'form-control',
            }),
            'dolgnost': Select(attrs={
                'class': 'form-control',
            }),
        }

accounts/views.py
from lib2to3.fixes.fix_input import context

from django.contrib.auth import login, authenticate, logout
from django.db.transaction import commit

from django.shortcuts import render, redirect
from .forms import LoginForm, RegisterForm
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import Phone
from .models import Profile, Podrazdelenie, Dolgnost

def user_login(request):
    if request.method == 'POST':

        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('home')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})


def registration(request):
    if request.method == 'GET':
        form = RegisterForm()
        return render(request, 'signup.html', {'form': form})

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():

            user = form.save(commit=False)
            user.username = user.username.lower()
            context = {
                'username': user.username,
                'form': Phone,
            }
            user.save()
            messages.success(request, 'You have singed up successfully.')
            login(request, user)

            return render(request, 'registration1.html', context=context)
        else:
            messages.success(request, 'You have singed up successfully.')
            return render(request, 'signup.html', {'form': form})

def logout_view(request):
    logout(request)

    return redirect('login')



def add_phone(request):

    if request.method == 'GET':
        form = Phone()
        return render(request, 'add_phone.html')

    if request.method == 'POST':
        form = Phone(request.POST)
        if form.is_valid():

            phone = form.save(commit=False)


            phone.save()
            return redirect('home')
        else:

            return render(request, 'add_phone.html', {'form': form})




def registration1(request):
    form = Phone()
    context = {
        'form': form
    }
    if request.method == 'POST':
        if 'username' in request.POST:
            form = Phone(request.POST)
            if form.is_valid:
                user = Profile.objects.get(user=User.objects.get(username=request.POST.get('username')))
                user.phone = request.POST.get('phone')
                user.podrazdelenie = Podrazdelenie.objects.get(id=request.POST.get('podrazdelenie'))
                user.dolgnost = Dolgnost.objects.get(id=request.POST.get('dolgnost'))
                user.save()
                return redirect('home')


    return render(request, 'registration1.html', context=context)

accounts/templates/add_phone.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block main %}



<form method="POST" novalidate>
              {% csrf_token %}



              <label for="id_phone">Введите номер телефона</label>
              <input type="tel" name="phone" id="id_phone" class="form-control">
              <label for="id_dolgnost">Выберите подразделение</label>
              <input type="text" name="dolgnost" id="id_dolgnost" class="form-control">

              <button class="btn btn-success" type="submit">Отправить</button>


</form>>

{% endblock %}

accounts/templates/base.html
{% load crispy_forms_tags %}



<!doctype  html>
<html  lang="en">
<head>
<link  rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"  crossorigin="anonymous">
<title>Django Authentication Example</title>
</head>
<body style="background-color: #d2cef5; min-width: 334px;">

          {% block main %}
          {% endblock %}
        </div>
      </div>
    </div>
  </main>



</body>
</html>

accounts/templates/registration1.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block main %}

<header style="box-shadow: 2px 2px 2px 1px rgba(0,0,0, .2);">
  <div class="container-fluid d-flex p-10" style="flex-direction: column;">
    <div class="row">
      <div class="col align-items-left">
        <img src="../../static/main/img/logoMH.png" style="width: 5rem; height: 5rem;" alt="">
      </div>
    </div>
  </div>
</header>
<main style="margin-top: 10rem;">
  <div class="container-fluid d-flex justify-content-center">
    <div class="row">
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h2>Регистрация</h2>
            
            <form method="POST" action="{% url 'registration1' %}">
              {% csrf_token %}
              <input value="{{username}}" name="username" disabled type="text">
             
            
              {% for field in form %}
              <p>
                {% if field.errors %}
              <ul class="errorlist">
                {% for error in field.errors %}
                <li>{{ error }}</li>
                {% endfor %}
              </ul>
              {% endif %}
              {{ field.label_tag }}<br> {{ field }}
              </p>
              {% endfor %}
              <button class="btn btn-success" name="username" style="margin-bottom: 2rem;" value="{{username}}" type="submit">Сохранить</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block main %}

<header style="box-shadow: 2px 2px 2px 1px rgba(0,0,0, .2);">
  <div class="container-fluid d-flex p-10" style="flex-direction: column;">
    <div class="row">
      <div class="col align-items-left">
        <img src="../../static/main/img/logoMH.png" style="width: 5rem; height: 5rem;" alt="">
      </div>
    </div>
  </div>
</header>
<main style="margin-top: 10rem;">
  <div class="container-fluid d-flex justify-content-center">
    <div class="row">
      <div class="col">
        <div class="card">
          <div class="card-body">
            
            <form method="POST" novalidate>
              {% csrf_token %}
              <h2>Регистрация</h2>
            
              {% for field in form %}
              <p>
                {% if field.errors %}
              <ul class="errorlist">
                {% for error in field.errors %}
                <li>{{ error }}</li>
                {% endfor %}
              </ul>
              {% endif %}
              {{ field.label_tag }}<br> {{ field }}
              </p>
              {% endfor %}
              <button class="btn btn-success" type="submit">Создать пользователя</button>
              <a href="{%url 'login' %}">Вход</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

{% endblock %}